/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

import Model.Answer;
import Model.Question;
import javax.swing.JOptionPane;

/**
 *
 * @author adrianrobak
 */
public class OpenQuestion extends javax.swing.JPanel {

    public void Clear(){
        AnswerText.setText(""); 
    } 
    
    Question Q;
    
    public void Initialization(Question Q){
        Clear();
        this.Q = Q;
        questionText.setText(Q.QuestionText);
    }
    /**
     * Creates new form OpenQuestion
     */
    public OpenQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AnswerText = new javax.swing.JTextArea();

        questionText.setText("TrescPytania");
        questionText.setName("questionText"); // NOI18N

        AnswerText.setColumns(20);
        AnswerText.setRows(5);
        jScrollPane1.setViewportView(AnswerText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionText, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionText, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AnswerText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel questionText;
    // End of variables declaration//GEN-END:variables

    boolean ValidateAnswer() {
        
        String val = AnswerText.getText();
        Boolean valb = val.equals("");
        
        if(!valb){
            return true;
        }
        else {
            JOptionPane.showMessageDialog(null, "You need to fill something.");
            return false;
        }
    }

    Answer GetAnswer() {
        Answer a = new Answer(Q.Id);        
        
        a.AnswerText = AnswerText.getText();
        
        return a;
    }
}
